.TH ucd 1 2015-01-12 "libucd Manuals" "User Commands"
.\" Process with
.\" nroff -man ucd.1
.\" 2015-01-12 Yunhui Fu <https://github.com/yhfudev>

.SH NAME
ucd \- Universal Charset Detector
.SH DESCRIPTION
ucd Command Line Tool
.SS "Usage:"
.HP
ucd [\fBOptions\fR] [\fBFile\fR]
.HP
[\fBFile\fR]
If file name(s) are not given, then read from STDIN.
.HP
\fB\-v\fR
Print version and build information.
.HP
\fB\-h\fR
Print help text.
.HP
.IP
.PP
ucd Command Line Tool

.SH AUTHORS
Yunhui Fu <https://github.com/yhfudev>

.SH "BUG REPORTS"
Use QnA board on https://github.com/yhfudev

.SH "SEE ALSO"

