.TH ucd 1 2015-01-12 "libucd Manuals" "User Commands"
.\" Process with
.\" nroff -man ucd.1
.\" 2015-01-12 Yunhui Fu <https://github.com/yhfudev>

.SH NAME
ucd \- 全能字符集探测

.SH "描述 (DESCRIPTION)"
ucd 的命令行工具

.SS "用法:"
.HP
ucd [\fB参数\fR] [\fB文件名\fR]
.HP
[\fB文件名\fR]
如果没有给出文件名，则从标准输入读取。
.HP
\fB\-v\fR
打印版本号和编译信息。
.HP
\fB\-h\fR
打印帮助信息.
.HP
.IP
.PP
ucd 的命令行工具

.SH "作者"
Yunhui Fu <https://github.com/yhfudev>

.SH "问题报告"
Use QnA board on https://github.com/yhfudev

.SH "参见"

